### ISSUE TITLE
Telegram stopped working

### ISSUE THREAD

**Issue by minGRID992020** [vasjen/fbtracker#4]
Hey, great job - but now it stopped sending to telegram at 10:30 am uk time on 19/November

**Comment by vasjen** [comment]
Hi there!
Thank you for reporting that the service was not working. Yes, there were issues with the website's security, and there wasn't enough time to fix it quickly.

The bot is now functioning as it did before. Last weekend, I had planned (and partially started) to update its operating algorithm, but due to access restrictions, I had to focus on restoring its functionality.

Therefore, I advise staying in touch and not missing out on the updated version of the bot.

Once again, thank you for notifying about the malfunction, and I apologize for the prolonged resolution of the issue
![image](https://github.com/vasjen/fbtracker/assets/103886550/5036fddc-4d30-4dac-a5bc-241269fb30ff)
